package com.sxt.ytwl.mapper;

import com.sxt.ytwl.model.Carriers;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface CarriersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carriers
     *
     * @mbggenerated Fri Feb 22 19:24:53 CST 2019
     */
    int deleteByPrimaryKey(Integer carriersid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carriers
     *
     * @mbggenerated Fri Feb 22 19:24:53 CST 2019
     */
    int insert(Carriers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carriers
     *
     * @mbggenerated Fri Feb 22 19:24:53 CST 2019
     */
    int insertSelective(Carriers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carriers
     *
     * @mbggenerated Fri Feb 22 19:24:53 CST 2019
     */
    Carriers selectByPrimaryKey(Integer carriersid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carriers
     *
     * @mbggenerated Fri Feb 22 19:24:53 CST 2019
     */
    int updateByPrimaryKeySelective(Carriers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carriers
     *
     * @mbggenerated Fri Feb 22 19:24:53 CST 2019
     */
    int updateByPrimaryKey(Carriers record);

    List<Carriers> getAllByPage(@Param("page") Integer page, @Param("size") Integer size, @Param("keyword") String keyword, @Param("uid") Integer userid);

    long getTotal(@Param("keyword") String keyword, @Param("uid") Integer userid);

    long getTotal2(@Param("state") Integer state,@Param("uid") Integer userid);

    List<Carriers> getAllByPage2(@Param("page") Integer page, @Param("size") Integer size, @Param("state") Integer state,@Param("uid") Integer userid);

    List<Carriers> getAllByPage3(@Param("page") Integer page, @Param("size") Integer size, @Param("state") Integer status);

    long getTotal3(@Param("state") Integer state);
}