package com.sxt.ytwl.mapper;

import com.sxt.ytwl.model.Logdic;

public interface LogdicMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logdic
     *
     * @mbggenerated Fri Feb 22 19:24:53 CST 2019
     */
    int deleteByPrimaryKey(Integer typeid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logdic
     *
     * @mbggenerated Fri Feb 22 19:24:53 CST 2019
     */
    int insert(Logdic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logdic
     *
     * @mbggenerated Fri Feb 22 19:24:53 CST 2019
     */
    int insertSelective(Logdic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logdic
     *
     * @mbggenerated Fri Feb 22 19:24:53 CST 2019
     */
    Logdic selectByPrimaryKey(Integer typeid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logdic
     *
     * @mbggenerated Fri Feb 22 19:24:53 CST 2019
     */
    int updateByPrimaryKeySelective(Logdic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logdic
     *
     * @mbggenerated Fri Feb 22 19:24:53 CST 2019
     */
    int updateByPrimaryKey(Logdic record);
}