package com.sxt.ytwl.mapper;

import com.sxt.ytwl.model.Syslog;
import com.sxt.ytwl.model.SyslogWithBLOBs;

public interface SyslogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table syslog
     *
     * @mbggenerated Fri Feb 22 19:24:53 CST 2019
     */
    int deleteByPrimaryKey(Integer logid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table syslog
     *
     * @mbggenerated Fri Feb 22 19:24:53 CST 2019
     */
    int insert(SyslogWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table syslog
     *
     * @mbggenerated Fri Feb 22 19:24:53 CST 2019
     */
    int insertSelective(SyslogWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table syslog
     *
     * @mbggenerated Fri Feb 22 19:24:53 CST 2019
     */
    SyslogWithBLOBs selectByPrimaryKey(Integer logid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table syslog
     *
     * @mbggenerated Fri Feb 22 19:24:53 CST 2019
     */
    int updateByPrimaryKeySelective(SyslogWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table syslog
     *
     * @mbggenerated Fri Feb 22 19:24:53 CST 2019
     */
    int updateByPrimaryKeyWithBLOBs(SyslogWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table syslog
     *
     * @mbggenerated Fri Feb 22 19:24:53 CST 2019
     */
    int updateByPrimaryKey(Syslog record);
}