package com.sxt.ytwl.model;

public class Contact {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contact.contactID
     *
     * @mbggenerated Fri Feb 22 19:24:53 CST 2019
     */
    private Integer contactid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contact.fk_truckID
     *
     * @mbggenerated Fri Feb 22 19:24:53 CST 2019
     */
    private Integer fkTruckid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contact.fk_driverID
     *
     * @mbggenerated Fri Feb 22 19:24:53 CST 2019
     */
    private Integer fkDriverid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contact.contactID
     *
     * @return the value of contact.contactID
     *
     * @mbggenerated Fri Feb 22 19:24:53 CST 2019
     */
    public Integer getContactid() {
        return contactid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contact.contactID
     *
     * @param contactid the value for contact.contactID
     *
     * @mbggenerated Fri Feb 22 19:24:53 CST 2019
     */
    public void setContactid(Integer contactid) {
        this.contactid = contactid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contact.fk_truckID
     *
     * @return the value of contact.fk_truckID
     *
     * @mbggenerated Fri Feb 22 19:24:53 CST 2019
     */
    public Integer getFkTruckid() {
        return fkTruckid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contact.fk_truckID
     *
     * @param fkTruckid the value for contact.fk_truckID
     *
     * @mbggenerated Fri Feb 22 19:24:53 CST 2019
     */
    public void setFkTruckid(Integer fkTruckid) {
        this.fkTruckid = fkTruckid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contact.fk_driverID
     *
     * @return the value of contact.fk_driverID
     *
     * @mbggenerated Fri Feb 22 19:24:53 CST 2019
     */
    public Integer getFkDriverid() {
        return fkDriverid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contact.fk_driverID
     *
     * @param fkDriverid the value for contact.fk_driverID
     *
     * @mbggenerated Fri Feb 22 19:24:53 CST 2019
     */
    public void setFkDriverid(Integer fkDriverid) {
        this.fkDriverid = fkDriverid;
    }
}