package com.sxt.ytwl.model;

import com.fasterxml.jackson.annotation.JsonFormat;

import java.util.Date;

public class Driver {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column driver.driverID
     *
     * @mbggenerated Fri Feb 22 19:24:53 CST 2019
     */
    private Integer driverid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column driver.name
     *
     * @mbggenerated Fri Feb 22 19:24:53 CST 2019
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column driver.sex
     *
     * @mbggenerated Fri Feb 22 19:24:53 CST 2019
     */
    private Integer sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column driver.birth
     *
     * @mbggenerated Fri Feb 22 19:24:53 CST 2019
     */
    private Date birth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column driver.phone
     *
     * @mbggenerated Fri Feb 22 19:24:53 CST 2019
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column driver.IDCard
     *
     * @mbggenerated Fri Feb 22 19:24:53 CST 2019
     */
    private String idcard;
    private Truckteam truckteam;

    public Truckteam getTruckteam() {
        return truckteam;
    }

    public void setTruckteam(Truckteam truckteam) {
        this.truckteam = truckteam;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column driver.fk_teamID
     *
     * @mbggenerated Fri Feb 22 19:24:53 CST 2019
     */
    private Integer fkTeamid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column driver.state
     *
     * @mbggenerated Fri Feb 22 19:24:53 CST 2019
     */
    private Integer state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column driver.remark
     *
     * @mbggenerated Fri Feb 22 19:24:53 CST 2019
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column driver.checkInTime
     *
     * @mbggenerated Fri Feb 22 19:24:53 CST 2019
     */
    private Date checkintime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column driver.isDelete
     *
     * @mbggenerated Fri Feb 22 19:24:53 CST 2019
     */
    private Integer isdelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column driver.alterTime
     *
     * @mbggenerated Fri Feb 22 19:24:53 CST 2019
     */
    private Date altertime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column driver.driverID
     *
     * @return the value of driver.driverID
     *
     * @mbggenerated Fri Feb 22 19:24:53 CST 2019
     */
    public Integer getDriverid() {
        return driverid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column driver.driverID
     *
     * @param driverid the value for driver.driverID
     *
     * @mbggenerated Fri Feb 22 19:24:53 CST 2019
     */
    public void setDriverid(Integer driverid) {
        this.driverid = driverid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column driver.name
     *
     * @return the value of driver.name
     *
     * @mbggenerated Fri Feb 22 19:24:53 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column driver.name
     *
     * @param name the value for driver.name
     *
     * @mbggenerated Fri Feb 22 19:24:53 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column driver.sex
     *
     * @return the value of driver.sex
     *
     * @mbggenerated Fri Feb 22 19:24:53 CST 2019
     */
    public Integer getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column driver.sex
     *
     * @param sex the value for driver.sex
     *
     * @mbggenerated Fri Feb 22 19:24:53 CST 2019
     */
    public void setSex(Integer sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column driver.birth
     *
     * @return the value of driver.birth
     *
     * @mbggenerated Fri Feb 22 19:24:53 CST 2019
     */
    @JsonFormat(pattern = "yyyy-MM-dd")
    public Date getBirth() {
        return birth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column driver.birth
     *
     * @param birth the value for driver.birth
     *
     * @mbggenerated Fri Feb 22 19:24:53 CST 2019
     */
    public void setBirth(Date birth) {
        this.birth = birth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column driver.phone
     *
     * @return the value of driver.phone
     *
     * @mbggenerated Fri Feb 22 19:24:53 CST 2019
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column driver.phone
     *
     * @param phone the value for driver.phone
     *
     * @mbggenerated Fri Feb 22 19:24:53 CST 2019
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column driver.IDCard
     *
     * @return the value of driver.IDCard
     *
     * @mbggenerated Fri Feb 22 19:24:53 CST 2019
     */
    public String getIdcard() {
        return idcard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column driver.IDCard
     *
     * @param idcard the value for driver.IDCard
     *
     * @mbggenerated Fri Feb 22 19:24:53 CST 2019
     */
    public void setIdcard(String idcard) {
        this.idcard = idcard == null ? null : idcard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column driver.fk_teamID
     *
     * @return the value of driver.fk_teamID
     *
     * @mbggenerated Fri Feb 22 19:24:53 CST 2019
     */
    public Integer getFkTeamid() {
        return fkTeamid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column driver.fk_teamID
     *
     * @param fkTeamid the value for driver.fk_teamID
     *
     * @mbggenerated Fri Feb 22 19:24:53 CST 2019
     */
    public void setFkTeamid(Integer fkTeamid) {
        this.fkTeamid = fkTeamid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column driver.state
     *
     * @return the value of driver.state
     *
     * @mbggenerated Fri Feb 22 19:24:53 CST 2019
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column driver.state
     *
     * @param state the value for driver.state
     *
     * @mbggenerated Fri Feb 22 19:24:53 CST 2019
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column driver.remark
     *
     * @return the value of driver.remark
     *
     * @mbggenerated Fri Feb 22 19:24:53 CST 2019
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column driver.remark
     *
     * @param remark the value for driver.remark
     *
     * @mbggenerated Fri Feb 22 19:24:53 CST 2019
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column driver.checkInTime
     *
     * @return the value of driver.checkInTime
     *
     * @mbggenerated Fri Feb 22 19:24:53 CST 2019
     */
    @JsonFormat(pattern = "yyyy-MM-dd")
    public Date getCheckintime() {
        return checkintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column driver.checkInTime
     *
     * @param checkintime the value for driver.checkInTime
     *
     * @mbggenerated Fri Feb 22 19:24:53 CST 2019
     */
    public void setCheckintime(Date checkintime) {
        this.checkintime = checkintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column driver.isDelete
     *
     * @return the value of driver.isDelete
     *
     * @mbggenerated Fri Feb 22 19:24:53 CST 2019
     */
    public Integer getIsdelete() {
        return isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column driver.isDelete
     *
     * @param isdelete the value for driver.isDelete
     *
     * @mbggenerated Fri Feb 22 19:24:53 CST 2019
     */
    public void setIsdelete(Integer isdelete) {
        this.isdelete = isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column driver.alterTime
     *
     * @return the value of driver.alterTime
     *
     * @mbggenerated Fri Feb 22 19:24:53 CST 2019
     */
    public Date getAltertime() {
        return altertime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column driver.alterTime
     *
     * @param altertime the value for driver.alterTime
     *
     * @mbggenerated Fri Feb 22 19:24:53 CST 2019
     */
    public void setAltertime(Date altertime) {
        this.altertime = altertime;
    }
}