package com.sxt.ytwl.model;

public class Goods {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.goodsID
     *
     * @mbggenerated Fri Feb 22 19:24:53 CST 2019
     */
    private Integer goodsid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.goodsName
     *
     * @mbggenerated Fri Feb 22 19:24:53 CST 2019
     */
    private String goodsname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.amount
     *
     * @mbggenerated Fri Feb 22 19:24:53 CST 2019
     */
    private Integer amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.weight
     *
     * @mbggenerated Fri Feb 22 19:24:53 CST 2019
     */
    private Float weight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.volume
     *
     * @mbggenerated Fri Feb 22 19:24:53 CST 2019
     */
    private Float volume;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.fk_carriersID
     *
     * @mbggenerated Fri Feb 22 19:24:53 CST 2019
     */
    private Integer fkCarriersid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.isDelete
     *
     * @mbggenerated Fri Feb 22 19:24:53 CST 2019
     */
    private Integer isdelete;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.goodsID
     *
     * @return the value of goods.goodsID
     *
     * @mbggenerated Fri Feb 22 19:24:53 CST 2019
     */
    public Integer getGoodsid() {
        return goodsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.goodsID
     *
     * @param goodsid the value for goods.goodsID
     *
     * @mbggenerated Fri Feb 22 19:24:53 CST 2019
     */
    public void setGoodsid(Integer goodsid) {
        this.goodsid = goodsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.goodsName
     *
     * @return the value of goods.goodsName
     *
     * @mbggenerated Fri Feb 22 19:24:53 CST 2019
     */
    public String getGoodsname() {
        return goodsname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.goodsName
     *
     * @param goodsname the value for goods.goodsName
     *
     * @mbggenerated Fri Feb 22 19:24:53 CST 2019
     */
    public void setGoodsname(String goodsname) {
        this.goodsname = goodsname == null ? null : goodsname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.amount
     *
     * @return the value of goods.amount
     *
     * @mbggenerated Fri Feb 22 19:24:53 CST 2019
     */
    public Integer getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.amount
     *
     * @param amount the value for goods.amount
     *
     * @mbggenerated Fri Feb 22 19:24:53 CST 2019
     */
    public void setAmount(Integer amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.weight
     *
     * @return the value of goods.weight
     *
     * @mbggenerated Fri Feb 22 19:24:53 CST 2019
     */
    public Float getWeight() {
        return weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.weight
     *
     * @param weight the value for goods.weight
     *
     * @mbggenerated Fri Feb 22 19:24:53 CST 2019
     */
    public void setWeight(Float weight) {
        this.weight = weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.volume
     *
     * @return the value of goods.volume
     *
     * @mbggenerated Fri Feb 22 19:24:53 CST 2019
     */
    public Float getVolume() {
        return volume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.volume
     *
     * @param volume the value for goods.volume
     *
     * @mbggenerated Fri Feb 22 19:24:53 CST 2019
     */
    public void setVolume(Float volume) {
        this.volume = volume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.fk_carriersID
     *
     * @return the value of goods.fk_carriersID
     *
     * @mbggenerated Fri Feb 22 19:24:53 CST 2019
     */
    public Integer getFkCarriersid() {
        return fkCarriersid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.fk_carriersID
     *
     * @param fkCarriersid the value for goods.fk_carriersID
     *
     * @mbggenerated Fri Feb 22 19:24:53 CST 2019
     */
    public void setFkCarriersid(Integer fkCarriersid) {
        this.fkCarriersid = fkCarriersid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.isDelete
     *
     * @return the value of goods.isDelete
     *
     * @mbggenerated Fri Feb 22 19:24:53 CST 2019
     */
    public Integer getIsdelete() {
        return isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.isDelete
     *
     * @param isdelete the value for goods.isDelete
     *
     * @mbggenerated Fri Feb 22 19:24:53 CST 2019
     */
    public void setIsdelete(Integer isdelete) {
        this.isdelete = isdelete;
    }
}