package com.sxt.ytwl.model;

public class Logdic {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column logdic.typeID
     *
     * @mbggenerated Fri Feb 22 19:24:53 CST 2019
     */
    private Integer typeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column logdic.typeName
     *
     * @mbggenerated Fri Feb 22 19:24:53 CST 2019
     */
    private String typename;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column logdic.typeID
     *
     * @return the value of logdic.typeID
     *
     * @mbggenerated Fri Feb 22 19:24:53 CST 2019
     */
    public Integer getTypeid() {
        return typeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column logdic.typeID
     *
     * @param typeid the value for logdic.typeID
     *
     * @mbggenerated Fri Feb 22 19:24:53 CST 2019
     */
    public void setTypeid(Integer typeid) {
        this.typeid = typeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column logdic.typeName
     *
     * @return the value of logdic.typeName
     *
     * @mbggenerated Fri Feb 22 19:24:53 CST 2019
     */
    public String getTypename() {
        return typename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column logdic.typeName
     *
     * @param typename the value for logdic.typeName
     *
     * @mbggenerated Fri Feb 22 19:24:53 CST 2019
     */
    public void setTypename(String typename) {
        this.typename = typename == null ? null : typename.trim();
    }
}