package com.sxt.ytwl.model;

public class Role {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.roleID
     *
     * @mbggenerated Fri Feb 22 19:24:53 CST 2019
     */
    private Integer roleid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.roleName
     *
     * @mbggenerated Fri Feb 22 19:24:53 CST 2019
     */
    private String rolename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.rolePurview
     *
     * @mbggenerated Fri Feb 22 19:24:53 CST 2019
     */
    private String rolepurview;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.roleID
     *
     * @return the value of role.roleID
     *
     * @mbggenerated Fri Feb 22 19:24:53 CST 2019
     */
    public Integer getRoleid() {
        return roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.roleID
     *
     * @param roleid the value for role.roleID
     *
     * @mbggenerated Fri Feb 22 19:24:53 CST 2019
     */
    public void setRoleid(Integer roleid) {
        this.roleid = roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.roleName
     *
     * @return the value of role.roleName
     *
     * @mbggenerated Fri Feb 22 19:24:53 CST 2019
     */
    public String getRolename() {
        return rolename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.roleName
     *
     * @param rolename the value for role.roleName
     *
     * @mbggenerated Fri Feb 22 19:24:53 CST 2019
     */
    public void setRolename(String rolename) {
        this.rolename = rolename == null ? null : rolename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.rolePurview
     *
     * @return the value of role.rolePurview
     *
     * @mbggenerated Fri Feb 22 19:24:53 CST 2019
     */
    public String getRolepurview() {
        return rolepurview;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.rolePurview
     *
     * @param rolepurview the value for role.rolePurview
     *
     * @mbggenerated Fri Feb 22 19:24:53 CST 2019
     */
    public void setRolepurview(String rolepurview) {
        this.rolepurview = rolepurview == null ? null : rolepurview.trim();
    }
}