package com.sxt.ytwl.model;

import com.fasterxml.jackson.annotation.JsonFormat;

import java.util.Date;

public class Scheduling {
    private Integer schedulingid;

    private Date starttime;

    private Integer fkCarriersid;

    private Integer fkTruckid;

    private Float oilcost;

    private Float toll;

    private Float fine;

    private Float othercost;

    private Float totalcost;

    private Integer fkUserid;

    private String remark;

    private Date checkintime;

    private Integer isdelete;

    private Date altertime;

    private Truck truck;

    private Carriers carriers;

    public Truck getTruck() {
        return truck;
    }

    public void setTruck(Truck truck) {
        this.truck = truck;
    }

    public Carriers getCarriers() {
        return carriers;
    }

    public void setCarriers(Carriers carriers) {
        this.carriers = carriers;
    }

    public Integer getSchedulingid() {
        return schedulingid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scheduling.schedulingID
     *
     * @param schedulingid the value for scheduling.schedulingID
     *
     * @mbggenerated Fri Feb 22 19:24:53 CST 2019
     */
    public void setSchedulingid(Integer schedulingid) {
        this.schedulingid = schedulingid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scheduling.startTime
     *
     * @return the value of scheduling.startTime
     *
     * @mbggenerated Fri Feb 22 19:24:53 CST 2019
     */
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    public Date getStarttime() {
        return starttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scheduling.startTime
     *
     * @param starttime the value for scheduling.startTime
     *
     * @mbggenerated Fri Feb 22 19:24:53 CST 2019
     */
    public void setStarttime(Date starttime) {
        this.starttime = starttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scheduling.fk_carriersID
     *
     * @return the value of scheduling.fk_carriersID
     *
     * @mbggenerated Fri Feb 22 19:24:53 CST 2019
     */
    public Integer getFkCarriersid() {
        return fkCarriersid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scheduling.fk_carriersID
     *
     * @param fkCarriersid the value for scheduling.fk_carriersID
     *
     * @mbggenerated Fri Feb 22 19:24:53 CST 2019
     */
    public void setFkCarriersid(Integer fkCarriersid) {
        this.fkCarriersid = fkCarriersid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scheduling.fk_truckID
     *
     * @return the value of scheduling.fk_truckID
     *
     * @mbggenerated Fri Feb 22 19:24:53 CST 2019
     */
    public Integer getFkTruckid() {
        return fkTruckid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scheduling.fk_truckID
     *
     * @param fkTruckid the value for scheduling.fk_truckID
     *
     * @mbggenerated Fri Feb 22 19:24:53 CST 2019
     */
    public void setFkTruckid(Integer fkTruckid) {
        this.fkTruckid = fkTruckid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scheduling.oilCost
     *
     * @return the value of scheduling.oilCost
     *
     * @mbggenerated Fri Feb 22 19:24:53 CST 2019
     */
    public Float getOilcost() {
        return oilcost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scheduling.oilCost
     *
     * @param oilcost the value for scheduling.oilCost
     *
     * @mbggenerated Fri Feb 22 19:24:53 CST 2019
     */
    public void setOilcost(Float oilcost) {
        this.oilcost = oilcost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scheduling.toll
     *
     * @return the value of scheduling.toll
     *
     * @mbggenerated Fri Feb 22 19:24:53 CST 2019
     */
    public Float getToll() {
        return toll;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scheduling.toll
     *
     * @param toll the value for scheduling.toll
     *
     * @mbggenerated Fri Feb 22 19:24:53 CST 2019
     */
    public void setToll(Float toll) {
        this.toll = toll;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scheduling.fine
     *
     * @return the value of scheduling.fine
     *
     * @mbggenerated Fri Feb 22 19:24:53 CST 2019
     */
    public Float getFine() {
        return fine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scheduling.fine
     *
     * @param fine the value for scheduling.fine
     *
     * @mbggenerated Fri Feb 22 19:24:53 CST 2019
     */
    public void setFine(Float fine) {
        this.fine = fine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scheduling.otherCost
     *
     * @return the value of scheduling.otherCost
     *
     * @mbggenerated Fri Feb 22 19:24:53 CST 2019
     */
    public Float getOthercost() {
        return othercost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scheduling.otherCost
     *
     * @param othercost the value for scheduling.otherCost
     *
     * @mbggenerated Fri Feb 22 19:24:53 CST 2019
     */
    public void setOthercost(Float othercost) {
        this.othercost = othercost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scheduling.totalCost
     *
     * @return the value of scheduling.totalCost
     *
     * @mbggenerated Fri Feb 22 19:24:53 CST 2019
     */
    public Float getTotalcost() {
        return totalcost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scheduling.totalCost
     *
     * @param totalcost the value for scheduling.totalCost
     *
     * @mbggenerated Fri Feb 22 19:24:53 CST 2019
     */
    public void setTotalcost(Float totalcost) {
        this.totalcost = totalcost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scheduling.fk_userID
     *
     * @return the value of scheduling.fk_userID
     *
     * @mbggenerated Fri Feb 22 19:24:53 CST 2019
     */
    public Integer getFkUserid() {
        return fkUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scheduling.fk_userID
     *
     * @param fkUserid the value for scheduling.fk_userID
     *
     * @mbggenerated Fri Feb 22 19:24:53 CST 2019
     */
    public void setFkUserid(Integer fkUserid) {
        this.fkUserid = fkUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scheduling.remark
     *
     * @return the value of scheduling.remark
     *
     * @mbggenerated Fri Feb 22 19:24:53 CST 2019
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scheduling.remark
     *
     * @param remark the value for scheduling.remark
     *
     * @mbggenerated Fri Feb 22 19:24:53 CST 2019
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scheduling.checkInTime
     *
     * @return the value of scheduling.checkInTime
     *
     * @mbggenerated Fri Feb 22 19:24:53 CST 2019
     */
    public Date getCheckintime() {
        return checkintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scheduling.checkInTime
     *
     * @param checkintime the value for scheduling.checkInTime
     *
     * @mbggenerated Fri Feb 22 19:24:53 CST 2019
     */
    @JsonFormat(pattern = "yyyy-MM-dd")
    public void setCheckintime(Date checkintime) {
        this.checkintime = checkintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scheduling.isDelete
     *
     * @return the value of scheduling.isDelete
     *
     * @mbggenerated Fri Feb 22 19:24:53 CST 2019
     */
    public Integer getIsdelete() {
        return isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scheduling.isDelete
     *
     * @param isdelete the value for scheduling.isDelete
     *
     * @mbggenerated Fri Feb 22 19:24:53 CST 2019
     */
    public void setIsdelete(Integer isdelete) {
        this.isdelete = isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scheduling.alterTime
     *
     * @return the value of scheduling.alterTime
     *
     * @mbggenerated Fri Feb 22 19:24:53 CST 2019
     */
    @JsonFormat(pattern = "yyyy-MM-dd")
    public Date getAltertime() {
        return altertime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scheduling.alterTime
     *
     * @param altertime the value for scheduling.alterTime
     *
     * @mbggenerated Fri Feb 22 19:24:53 CST 2019
     */
    public void setAltertime(Date altertime) {
        this.altertime = altertime;
    }
}