package com.sxt.ytwl.model;

import java.util.Date;

public class Syslog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column syslog.logID
     *
     * @mbggenerated Fri Feb 22 19:24:53 CST 2019
     */
    private Integer logid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column syslog.fk_typeID
     *
     * @mbggenerated Fri Feb 22 19:24:53 CST 2019
     */
    private Integer fkTypeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column syslog.fk_userID
     *
     * @mbggenerated Fri Feb 22 19:24:53 CST 2019
     */
    private Integer fkUserid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column syslog.procName
     *
     * @mbggenerated Fri Feb 22 19:24:53 CST 2019
     */
    private String procname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column syslog.IP
     *
     * @mbggenerated Fri Feb 22 19:24:53 CST 2019
     */
    private String ip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column syslog.checkInTime
     *
     * @mbggenerated Fri Feb 22 19:24:53 CST 2019
     */
    private Date checkintime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column syslog.isException
     *
     * @mbggenerated Fri Feb 22 19:24:53 CST 2019
     */
    private Integer isexception;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column syslog.logID
     *
     * @return the value of syslog.logID
     *
     * @mbggenerated Fri Feb 22 19:24:53 CST 2019
     */
    public Integer getLogid() {
        return logid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column syslog.logID
     *
     * @param logid the value for syslog.logID
     *
     * @mbggenerated Fri Feb 22 19:24:53 CST 2019
     */
    public void setLogid(Integer logid) {
        this.logid = logid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column syslog.fk_typeID
     *
     * @return the value of syslog.fk_typeID
     *
     * @mbggenerated Fri Feb 22 19:24:53 CST 2019
     */
    public Integer getFkTypeid() {
        return fkTypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column syslog.fk_typeID
     *
     * @param fkTypeid the value for syslog.fk_typeID
     *
     * @mbggenerated Fri Feb 22 19:24:53 CST 2019
     */
    public void setFkTypeid(Integer fkTypeid) {
        this.fkTypeid = fkTypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column syslog.fk_userID
     *
     * @return the value of syslog.fk_userID
     *
     * @mbggenerated Fri Feb 22 19:24:53 CST 2019
     */
    public Integer getFkUserid() {
        return fkUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column syslog.fk_userID
     *
     * @param fkUserid the value for syslog.fk_userID
     *
     * @mbggenerated Fri Feb 22 19:24:53 CST 2019
     */
    public void setFkUserid(Integer fkUserid) {
        this.fkUserid = fkUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column syslog.procName
     *
     * @return the value of syslog.procName
     *
     * @mbggenerated Fri Feb 22 19:24:53 CST 2019
     */
    public String getProcname() {
        return procname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column syslog.procName
     *
     * @param procname the value for syslog.procName
     *
     * @mbggenerated Fri Feb 22 19:24:53 CST 2019
     */
    public void setProcname(String procname) {
        this.procname = procname == null ? null : procname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column syslog.IP
     *
     * @return the value of syslog.IP
     *
     * @mbggenerated Fri Feb 22 19:24:53 CST 2019
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column syslog.IP
     *
     * @param ip the value for syslog.IP
     *
     * @mbggenerated Fri Feb 22 19:24:53 CST 2019
     */
    public void setIp(String ip) {
        this.ip = ip == null ? null : ip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column syslog.checkInTime
     *
     * @return the value of syslog.checkInTime
     *
     * @mbggenerated Fri Feb 22 19:24:53 CST 2019
     */
    public Date getCheckintime() {
        return checkintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column syslog.checkInTime
     *
     * @param checkintime the value for syslog.checkInTime
     *
     * @mbggenerated Fri Feb 22 19:24:53 CST 2019
     */
    public void setCheckintime(Date checkintime) {
        this.checkintime = checkintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column syslog.isException
     *
     * @return the value of syslog.isException
     *
     * @mbggenerated Fri Feb 22 19:24:53 CST 2019
     */
    public Integer getIsexception() {
        return isexception;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column syslog.isException
     *
     * @param isexception the value for syslog.isException
     *
     * @mbggenerated Fri Feb 22 19:24:53 CST 2019
     */
    public void setIsexception(Integer isexception) {
        this.isexception = isexception;
    }
}