package com.sxt.ytwl.model;

public class SyslogWithBLOBs extends Syslog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column syslog.behavior
     *
     * @mbggenerated Fri Feb 22 19:24:53 CST 2019
     */
    private String behavior;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column syslog.parameters
     *
     * @mbggenerated Fri Feb 22 19:24:53 CST 2019
     */
    private String parameters;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column syslog.exception
     *
     * @mbggenerated Fri Feb 22 19:24:53 CST 2019
     */
    private String exception;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column syslog.behavior
     *
     * @return the value of syslog.behavior
     *
     * @mbggenerated Fri Feb 22 19:24:53 CST 2019
     */
    public String getBehavior() {
        return behavior;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column syslog.behavior
     *
     * @param behavior the value for syslog.behavior
     *
     * @mbggenerated Fri Feb 22 19:24:53 CST 2019
     */
    public void setBehavior(String behavior) {
        this.behavior = behavior == null ? null : behavior.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column syslog.parameters
     *
     * @return the value of syslog.parameters
     *
     * @mbggenerated Fri Feb 22 19:24:53 CST 2019
     */
    public String getParameters() {
        return parameters;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column syslog.parameters
     *
     * @param parameters the value for syslog.parameters
     *
     * @mbggenerated Fri Feb 22 19:24:53 CST 2019
     */
    public void setParameters(String parameters) {
        this.parameters = parameters == null ? null : parameters.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column syslog.exception
     *
     * @return the value of syslog.exception
     *
     * @mbggenerated Fri Feb 22 19:24:53 CST 2019
     */
    public String getException() {
        return exception;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column syslog.exception
     *
     * @param exception the value for syslog.exception
     *
     * @mbggenerated Fri Feb 22 19:24:53 CST 2019
     */
    public void setException(String exception) {
        this.exception = exception == null ? null : exception.trim();
    }
}