package com.sxt.ytwl.model;

import com.fasterxml.jackson.annotation.JsonFormat;

import java.util.Date;

public class Truckteam {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column truckteam.teamID
     *
     * @mbggenerated Fri Feb 22 19:24:53 CST 2019
     */
    private Integer teamid;

    private String teamname;

    private String leader;

    private String remark;

    private Date checkintime;

    private Integer isdelete;

    private Date altertime;

    public Integer getTeamid() {
        return teamid;
    }

    public void setTeamid(Integer teamid) {
        this.teamid = teamid;
    }

    public String getTeamname() {
        return teamname;
    }

    public void setTeamname(String teamname) {
        this.teamname = teamname == null ? null : teamname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column truckteam.leader
     *
     * @return the value of truckteam.leader
     *
     * @mbggenerated Fri Feb 22 19:24:53 CST 2019
     */
    public String getLeader() {
        return leader;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column truckteam.leader
     *
     * @param leader the value for truckteam.leader
     *
     * @mbggenerated Fri Feb 22 19:24:53 CST 2019
     */
    public void setLeader(String leader) {
        this.leader = leader == null ? null : leader.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column truckteam.remark
     *
     * @return the value of truckteam.remark
     *
     * @mbggenerated Fri Feb 22 19:24:53 CST 2019
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column truckteam.remark
     *
     * @param remark the value for truckteam.remark
     *
     * @mbggenerated Fri Feb 22 19:24:53 CST 2019
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column truckteam.checkInTime
     *
     * @return the value of truckteam.checkInTime
     *
     * @mbggenerated Fri Feb 22 19:24:53 CST 2019
     */
    @JsonFormat(pattern = "yyyy-MM-dd")
    public Date getCheckintime() {
        return checkintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column truckteam.checkInTime
     *
     * @param checkintime the value for truckteam.checkInTime
     *
     * @mbggenerated Fri Feb 22 19:24:53 CST 2019
     */
    public void setCheckintime(Date checkintime) {
        this.checkintime = checkintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column truckteam.isDelete
     *
     * @return the value of truckteam.isDelete
     *
     * @mbggenerated Fri Feb 22 19:24:53 CST 2019
     */
    public Integer getIsdelete() {
        return isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column truckteam.isDelete
     *
     * @param isdelete the value for truckteam.isDelete
     *
     * @mbggenerated Fri Feb 22 19:24:53 CST 2019
     */
    public void setIsdelete(Integer isdelete) {
        this.isdelete = isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column truckteam.alterTime
     *
     * @return the value of truckteam.alterTime
     *
     * @mbggenerated Fri Feb 22 19:24:53 CST 2019
     */
    @JsonFormat(pattern = "yyyy-MM-dd")
    public Date getAltertime() {
        return altertime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column truckteam.alterTime
     *
     * @param altertime the value for truckteam.alterTime
     *
     * @mbggenerated Fri Feb 22 19:24:53 CST 2019
     */
    public void setAltertime(Date altertime) {
        this.altertime = altertime;
    }
}